### ISSUE TITLE
Update Messaging System for DAQ MainTask to Queue or Buffer

### ISSUE THREAD

**Issue by davinbirdi** [UBC-Rocket/WB-DAQ-Firmware#27]
From Pull Request

I implemented a shitty circular buffer somewhere in the FC FW ([here](https://github.com/UBC-Rocket/Whistler-Blackcomb-v2/blob/master/common/src/buffer.c)). Take a look and see if it would be useful to port over here, unless of course there is some non-shitty solution you know of and are already planning on using.

_Originally posted by @Esouder in https://github.com/UBC-Rocket/WB-DAQ-Firmware/pull/26#discussion_r877788731_

**Comment by Esouder** [comment]
We talked about this on Sunday (the 4th of September 2022), and it sounded like we settled on implementing this by way of that circular buffer that's already written. Of course still open to better alternatives if we find any.

I marked this as a 'good first issue' per our Sunday meeting as well.
